### ISSUE TITLE
Please Add SkypeOnline

### ISSUE THREAD

**Issue by Scott-som** [blindzero/Connect-MS365#24]
**Describe the solution you'd like**
Please add SkypeOnline support. There is a lot of Teams related things that can only be done via Skype.

**Describe alternatives you've considered**
I currently use a wrapper for New-CsOnlineSession, integration would be great.

**Additional context**
https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector

**Comment by blindzero** [comment]
drawbacks:
- no online Module available
- need to have a MSI package installed, needs Test- & Install-functions for this
- installer need confirmation

Maybe only user note if module is not available in system to be installed manually with link pointing directly to download page.

**Comment by Scott-som** [comment]
Could do a test if New-CsOnlineSession exists and if not put the download link in the error message.

**Comment by blindzero** [comment]
> Could do a test if New-CsOnlineSession exists and if not put the download link in the error message.

yeah, something like this...little drawback, but well...;)
