### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by FaganSC** [blindzero/Connect-MS365#25]
I'd happy to contribute. I have been working on a similar module but using Certificates for seamless authentication.

**Comment by blindzero** [comment]
Hi @FaganSC,

glad to hear that! I already noticed your Fork, nice.
Do you want to contribute with code? I am glad to receive your PR, e.g. if you want to add certificate support for authentication. As far as I've seen it, certificate authentication is only available for AD?

Best,
Matthias

**Comment by FaganSC** [comment]
Yea that would be helpful to write the contribute page. I haven't worked with the build and testing process your using so a little help getting setup would be great.

I have successfully setup several of the modules to connect using my setup with certificates and would be happy to add to your module.

**Comment by blindzero** [comment]
Hi @FaganSC 
I added the CONTRIBUTE documentation, do you want to have a look?
About certificate authentication: do you want to create a separate feature request for it?
Is it just available for Azure of for all services? Does it should be linked to #23 (user configuration file)?
